//
//  VocabularyList.swift
//  SimpleFlashcards
//
//  Created by Jane Madsen on 12/11/24.


// MARK: Instructions
// Each day, we will have a word of the day. Take a moment at the beginning of class to add the word to your vocabulary list here. (Feel free to add other words as well!)
// It's important that your syntax is correct. Several examples are provided below for you to refer to.
// To create a Vocab object, you only need to provide the word. All other fields are optional. For example, for a word with only a definition, you could type:

let exampleVocab = Vocab(word: "compiler", definition: "A program that translates human readable source code into binary.")

// If you get an error, check that your quotation marks, colons, brackets, parentheses, and commas are all placed correctly. Feel free to ask for help if you get stuck.
// To add images to your vocab, you'll need to first add them to the Assets folder. Then, set the referenceImage string to the name of the image in that folder.
// Ask for help if needed!


// MARK: Vocab Model and List

import Foundation

struct Vocab {
    var word: String
    var definition: String = ""
    var synonyms: [String] = []
    var notes: [String] = []
    var referenceImage: String = ""
    
    // Add words to your vocabulary list here. The order they are in below is the order they will appear in the app.
    static let list: [Vocab] = [
        Vocab(
            word: "constants",
            definition: "A constant is a value that cannot be altered during the execution of a program.",
            synonyms: ["Immutable Value"],
            notes: ["Declared using the 'let' keyword in Swift."],
            referenceImage: "constant"
        ),
        Vocab(
            word: "variables",
            definition: "A variable is a named storage that can hold a value and whose value can be changed during program execution.",
            synonyms: ["Mutable Value"],
            notes: ["Declared using the 'var' keyword in Swift."],
            referenceImage: "variable"
        ),
        Vocab(
            word: "strings",
            definition: "A string is a sequence of characters used to represent text.",
            synonyms: ["Text", "Character Sequence"],
            notes: ["In Swift, strings are declared using double quotes (\" \")."],
            referenceImage: "string"
        ),
        Vocab(
            word: "functions",
            definition: "A function is a reusable block of code that performs a specific task.",
            synonyms: ["Method", "Procedure"],
            notes: ["Defined using the 'func' keyword in Swift."],
            referenceImage: "func"
        ),
        Vocab(
            word: "arrays",
            definition: "An array is a collection of elements stored in a specific order.",
            synonyms: ["List", "Sequence"],
            notes: ["Arrays in Swift are zero-indexed and declared using square brackets []."],
            referenceImage: "array"
        ),
        Vocab(
            word: "methods",
            definition: "A method is a function associated with a specific type, such as a class, struct, or enum.",
            synonyms: ["Member Function"],
            notes: ["Methods are called on instances of a type."],
            referenceImage: "method"
        ),
        Vocab(
            word: "classes",
            definition: "A class is a blueprint for creating objects, providing initial values for properties and implementations of behavior.",
            synonyms: ["Object Blueprint"],
            notes: ["Classes support inheritance and are declared using the 'class' keyword in Swift."],
            referenceImage: "class"
        ),
        Vocab(
            word: "structs",
            definition: "A struct is a value type that encapsulates properties and methods.",
            synonyms: ["Structure", "Value Type"],
            notes: ["Structs in Swift are declared using the 'struct' keyword and are copied when assigned."],
            referenceImage: "struct"
        ),
        Vocab(
          word: "IDE",
          definition: "integrated Development Evironment: where you wirte your code.",
          notes: ["Xcode is an IDE"]),
        Vocab(
          word: "Compiler",
          definition: "A program that translates human source code into machine readable binary code",
          notes: [""]),
        Vocab(
          word: "Console",
          definition: "An interface within XCODE where developers can interact with runtime output generated by their application",
          notes:[""]),
        Vocab(
          word: "Syntax",
          definition: "The rules that define the organization of symbols and words that is considered correct in a language",
          notes: [""]),
        Vocab(
          word: "Object",
          definition: "A collection of state, behavior, and identity encapsulated into one item", notes: [""]),
        Vocab(word: "Instance",
           definition: "the live representation of your blueprint(class/struct)",
           notes:[""]),
        Vocab(
          word: "Pointer",
          definition: "A value that points to the location in memory of where another value is stored",
              notes:[""]),
        Vocab(
            word: "runtime",
            definition: "Runtime is the period during which a program is executing and actively performing tasks.",
            synonyms: ["Execution time", "Live state"],
            notes: ["Errors that occur during runtime (not while compiling) are called runtime errors."],
            referenceImage: "runtime"
        ),
        Vocab(
            word: "literal",
            definition: "A fixed value in the code, such as numbers, strings, and booleans.",
            synonyms: ["hard code", ""],
            notes: ["Any time the programmer enters the value instead of using computed values or user input. Examples: 42, \"username\", true"],
            referenceImage: "literal"
        ),
        Vocab(
            word: "interpolation",
            definition: "Embedding variables or expressions in a string literal.",
            synonyms: ["Insertion", ""],
            notes: ["using calculation to create customizeable text"],
            referenceImage: "interpolation"
        ),
        Vocab(
            word: "model",
            definition: "A representation of data and its associated logic",
            synonyms: ["Data",],
            notes: ["Swift uses structs and classes as models"],
            referenceImage: "model"
        ),
        Vocab(
            word: "conditional",
            definition: "Code logic that executes different paths based on a set of conditions.",
            synonyms: ["Branching","decision making"],
            notes: ["if else and switch"],
            referenceImage: "conditional"
        ),
        Vocab(
            word: "parameter",
            definition: "A variable passed into a function or method to provide input data",
            synonyms: [],
            notes: ["We often describe parameters as being \"passed in\" to a func "],
            referenceImage: "conditional"
        ),
        Vocab(
            word: "method",
            definition: "A set of instructions that perform a specific action on an object",
            synonyms: ["function"],
            notes: ["Dont have to be related to an object. Can be global in swift "],
            referenceImage: "method"
        ),
        Vocab(
            word: "command line interface",
            definition: "A text based interface for interacting with software and the operating system.",
            synonyms: ["CLI", "Terminal"],
            notes: ["As opposed to G.U.I. (graphical user interface)"],
            referenceImage: "command line interface"
        ),
        Vocab(
            word: "DVCS distributed version control system",
            definition: "A tool for managing source code across multiple developers and machines",
            synonyms: ["source control"],
            notes: ["git"],
            referenceImage: "distributed version control system"
        ),
        Vocab(
            word: "property",
            definition: "A variable or value associated with an object (class or struct)",
            synonyms: ["attribute", "field"],
            notes: ["can be stored or computed"],
            referenceImage: "property"
        ),
        Vocab(
            word: "initializer",
            definition: " A special function that prepares an instance of a class or struct",
            synonyms: ["Constructor", "Instantiator"],
            notes: [".init()", "()"],
            referenceImage: "initializer"
        ),
        Vocab(
            word: "immutable",
            definition: "A value or variable that cannot be changed after initialization",
            synonyms: ["constant", "unchangeable"],
            notes: ["LET declares immutability", "Class pointers are immutable when declared with let, but not their properties"],
            referenceImage: "immutable"
        ),
        Vocab(
            word: "function signature",
            definition: "The name, parameters, and return type of a function",
            synonyms: ["method signature", "definition"],
            notes: ["func thisIsTheFuncSigLine(_ int: Int) -> Int {"],
            referenceImage: "control flow"
        ),
        Vocab(
            word: "control flow",
            definition: "The order in which individual statements or blocks of code are executed",
            synonyms: ["execution order", "logic flow"],
            notes: ["loops and conditionals dictate control flow"],
            referenceImage: "control flow"
        ),
        Vocab(
            word: "nested",
            definition: "Arranged in a hierarchical structure",
            synonyms: [""],
            notes: ["This view is \"nested" in its super view"],
            referenceImage: "control flow"
        )
    ]
}
